import { User, Issue, Comment } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Citizen',
    email: 'citizen@demo.com',
    role: 'citizen',
    phone: '+1234567890',
    password: 'demo123',
  },
  {
    id: '2',
    name: 'Jane Staff',
    email: 'staff@demo.com',
    role: 'staff',
    phone: '+1234567891',
    department: 'Roads & Infrastructure',
    password: 'demo123',
  },
  {
    id: '3',
    name: 'Admin User',
    email: 'admin@demo.com',
    role: 'admin',
    phone: '+1234567892',
    password: 'demo123',
  },
  {
    id: '4',
    name: 'Mike Worker',
    email: 'mike@demo.com',
    role: 'staff',
    phone: '+1234567893',
    department: 'Electricity & Power',
    password: 'demo123',
  },
  {
    id: '5',
    name: 'Sarah Staff',
    email: 'sarah@demo.com',
    role: 'staff',
    phone: '+1234567894',
    department: 'Water Supply',
    password: 'demo123',
  },
  {
    id: '6',
    name: 'Tom Sanchez',
    email: 'tom@demo.com',
    role: 'staff',
    phone: '+1234567895',
    department: 'Sanitation & Waste',
    password: 'demo123',
  },
  {
    id: '7',
    name: 'Lisa Public',
    email: 'lisa@demo.com',
    role: 'staff',
    phone: '+1234567896',
    department: 'Public Works',
    password: 'demo123',
  },
  {
    id: '8',
    name: 'Robert Roads',
    email: 'robert@demo.com',
    role: 'staff',
    phone: '+1234567897',
    department: 'Roads & Infrastructure',
    password: 'demo123',
  },
];

export const initialIssues: Issue[] = [
  {
    id: '1',
    title: 'Large Pothole on Main Street',
    description: 'There is a dangerous pothole near the intersection of Main St and 5th Ave. It has been causing damage to vehicles.',
    category: 'road',
    status: 'in_progress',
    location: 'Main St & 5th Ave',
    latitude: 40.7128,
    longitude: -74.0060,
    imageUrl: 'https://images.unsplash.com/photo-1469510090920-fd33379d1f7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaXR5JTIwaW5mcmFzdHJ1Y3R1cmUlMjBwb3Rob2xlfGVufDF8fHx8MTc2MTgzOTMxMnww&ixlib=rb-4.1.0&q=80&w=1080',
    reportedBy: '1',
    reporterName: 'John Citizen',
    assignedTo: '2',
    assignedToName: 'Jane Staff',
    department: 'Roads & Infrastructure',
    createdAt: '2025-10-25T10:30:00Z',
    updatedAt: '2025-10-28T14:20:00Z',
    upvotes: ['1', '4', '5'],
    upvoteCount: 3,
    priority: 'normal',
    slaDeadline: '2025-10-27T10:30:00Z',
    isOverdue: false,
  },
  {
    id: '2',
    title: 'Street Light Not Working',
    description: 'The street light on Elm Street has been out for a week, making the area very dark at night.',
    category: 'streetlight',
    status: 'inspection_scheduled',
    location: 'Elm Street, near Park',
    imageUrl: 'https://images.unsplash.com/photo-1649621990430-20f26720ca2e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXQlMjBsaWdodCUyMHJlcGFpcnxlbnwxfHx8fDE3NjE4MzkzMTJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    reportedBy: '1',
    reporterName: 'John Citizen',
    assignedTo: '4',
    assignedToName: 'Mike Worker',
    department: 'Electricity & Power',
    createdAt: '2025-10-28T09:15:00Z',
    updatedAt: '2025-10-29T10:00:00Z',
    upvotes: ['1', '5'],
    upvoteCount: 2,
  },
  {
    id: '3',
    title: 'Water Leakage on Oak Avenue',
    description: 'Continuous water leakage from underground pipe. Water is being wasted and creating muddy conditions.',
    category: 'water',
    status: 'resolved',
    location: 'Oak Avenue, Block 3',
    reportedBy: '1',
    reporterName: 'John Citizen',
    assignedTo: '5',
    assignedToName: 'Sarah Staff',
    department: 'Water Supply',
    createdAt: '2025-10-20T11:00:00Z',
    updatedAt: '2025-10-27T16:45:00Z',
    resolvedAt: '2025-10-27T16:45:00Z',
    resolutionNote: 'Pipe replaced successfully. Issue resolved.',
    upvotes: ['1'],
    upvoteCount: 1,
    feedback: {
      userId: '1',
      userName: 'John Citizen',
      rating: 5,
      comment: 'Excellent work! The team was professional and quick.',
      createdAt: '2025-10-27T18:30:00Z',
    },
  },
  {
    id: '4',
    title: 'Garbage Not Collected',
    description: 'Garbage bins have not been emptied for 3 days in our residential area.',
    category: 'sanitation',
    status: 'pending',
    location: 'Residential Area, Block 12',
    reportedBy: '1',
    reporterName: 'John Citizen',
    assignedTo: '6',
    assignedToName: 'Tom Sanchez',
    department: 'Sanitation & Waste',
    createdAt: '2025-10-29T08:00:00Z',
    updatedAt: '2025-10-29T08:00:00Z',
    upvotes: ['1', '4', '5', '6'],
    upvoteCount: 4,
  },
  {
    id: '5',
    title: 'Blocked Drainage System',
    description: 'Drainage is blocked causing water accumulation during rain. Risk of flooding.',
    category: 'drainage',
    status: 'inspection_scheduled',
    location: 'Park Lane, Section A',
    reportedBy: '1',
    reporterName: 'John Citizen',
    assignedTo: '7',
    assignedToName: 'Lisa Public',
    department: 'Public Works',
    createdAt: '2025-10-26T13:30:00Z',
    updatedAt: '2025-10-29T10:00:00Z',
    upvotes: ['1', '5', '6', '7'],
    upvoteCount: 4,
  },
];

export const initialComments: Comment[] = [
  {
    id: '1',
    issueId: '1',
    userId: '2',
    userName: 'Jane Staff',
    userRole: 'staff',
    message: 'We have started working on this issue. Expected completion in 2 days.',
    createdAt: '2025-10-28T14:20:00Z',
  },
  {
    id: '2',
    issueId: '1',
    userId: '1',
    userName: 'John Citizen',
    userRole: 'citizen',
    message: 'Thank you for the update!',
    createdAt: '2025-10-28T15:00:00Z',
  },
  {
    id: '3',
    issueId: '3',
    userId: '5',
    userName: 'Sarah Staff',
    userRole: 'staff',
    message: 'Issue has been resolved. We replaced the damaged pipe section.',
    createdAt: '2025-10-27T16:45:00Z',
  },
  {
    id: '4',
    issueId: '3',
    userId: '1',
    userName: 'John Citizen',
    userRole: 'citizen',
    message: 'Great work! The leakage has stopped completely.',
    createdAt: '2025-10-27T18:00:00Z',
  },
];

// Demo credentials
export const demoCredentials = {
  citizen: { email: 'citizen@demo.com', password: 'demo123' },
  staff: { email: 'staff@demo.com', password: 'demo123' },
  admin: { email: 'admin@demo.com', password: 'demo123' },
};
